// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using System;

namespace osu.Framework.Audio.EzLatency
{
#nullable disable

    public struct EzLatencyInputData
    {
        /// <summary>
        /// Unique correlation ID linking input/judge/playback events that belong together.
        /// Generated by EzLatencyAnalyzer on each RecordInputData call.
        /// </summary>
        public Guid CorrelationId;

        public double InputTime;
        public object KeyValue;
        public double JudgeTime;

        public double PlaybackTime;

        // Consider input+playback or input+judge as valid for best-effort measurements.
        public bool IsValid => InputTime > 0 && (PlaybackTime > 0 || JudgeTime > 0);

        /// <summary>
        /// Whether this slot is currently occupied by an unprocessed input event.
        /// </summary>
        public bool IsOccupied => InputTime > 0 && CorrelationId != Guid.Empty;

        /// <summary>
        /// Whether this entry has been fully processed (correlation ID cleared).
        /// </summary>
        public bool IsFree => CorrelationId == Guid.Empty;

        /// <summary>
        /// Maximum reasonable time (ms) between Input and Playback for a valid measurement.
        /// Events exceeding this threshold are considered mismatched (belong to different logical events)
        /// and should be discarded.
        /// </summary>
        public const double MAX_REASONABLE_INPUT_TO_PLAYBACK_MS = 5.0;

        /// <summary>
        /// Maximum reasonable time (ms) between Input and Judge for a valid measurement.
        /// </summary>
        public const double MAX_REASONABLE_INPUT_TO_JUDGE_MS = 5000.0;
    }
}
